# Solution build

trigger:
- develop

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:

- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    msbuildArchitecture: 'x64'
    configuration: '$(buildConfiguration)'

#- task: XamarinAndroid@1
#  inputs:
#    projectFile: '**/*Droid*.csproj'
#    outputDirectory: '$(outputDirectory)'
#    configuration: '$(buildConfiguration)'
