//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor
//     https://github.com/msawczyn/EFDesigner
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Tripplanner.DatabaseDesign
{
   public partial class Activity
   {
      partial void Init();

      /// <summary>
      /// Default constructor. Protected due to required properties, but present because EF needs it.
      /// </summary>
      protected Activity()
      {
         Init();
      }

      /// <summary>
      /// Public constructor with required data
      /// </summary>
      /// <param name="place"></param>
      /// <param name="_trip0"></param>
      public Activity(string place, global::Tripplanner.DatabaseDesign.Trip _trip0)
      {
         if (string.IsNullOrEmpty(place)) throw new ArgumentNullException(nameof(place));
         this.Place = place;
         if (_trip0 == null) throw new ArgumentNullException(nameof(_trip0));
         _trip0.Sightseeings.Add(this);

         Init();
      }

      /// <summary>
      /// Static create function (for use in LINQ queries, etc.)
      /// </summary>
      /// <param name="place"></param>
      /// <param name="_trip0"></param>
      public static Activity Create(string place, global::Tripplanner.DatabaseDesign.Trip _trip0)
      {
         return new Activity(place, _trip0);
      }

      /*************************************************************************
       * Persistent properties
       *************************************************************************/

      /// <summary>
      /// Identity, Required, Indexed
      /// </summary>
      [Key]
      [Required]
      public int Id { get; set; }

      /// <summary>
      /// Required
      /// </summary>
      [Required]
      public string Place { get; set; }

      public DateTime? Time { get; set; }

      /*************************************************************************
       * Persistent navigation properties
       *************************************************************************/

   }
}

