//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor
//     https://github.com/msawczyn/EFDesigner
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Tripplanner.DatabaseDesign
{
   public partial class CustomItem
   {
      partial void Init();

      /// <summary>
      /// Default constructor. Protected due to required properties, but present because EF needs it.
      /// </summary>
      protected CustomItem()
      {
         Init();
      }

      /// <summary>
      /// Public constructor with required data
      /// </summary>
      /// <param name="key"></param>
      /// <param name="value"></param>
      /// <param name="_tripinfo0"></param>
      public CustomItem(string key, string value, global::Tripplanner.DatabaseDesign.TripInfo _tripinfo0)
      {
         if (string.IsNullOrEmpty(key)) throw new ArgumentNullException(nameof(key));
         this.Key = key;
         if (string.IsNullOrEmpty(value)) throw new ArgumentNullException(nameof(value));
         this.Value = value;
         if (_tripinfo0 == null) throw new ArgumentNullException(nameof(_tripinfo0));
         _tripinfo0.CustomItems.Add(this);

         Init();
      }

      /// <summary>
      /// Static create function (for use in LINQ queries, etc.)
      /// </summary>
      /// <param name="key"></param>
      /// <param name="value"></param>
      /// <param name="_tripinfo0"></param>
      public static CustomItem Create(string key, string value, global::Tripplanner.DatabaseDesign.TripInfo _tripinfo0)
      {
         return new CustomItem(key, value, _tripinfo0);
      }

      /*************************************************************************
       * Persistent properties
       *************************************************************************/

      /// <summary>
      /// Identity, Required, Indexed
      /// </summary>
      [Key]
      [Required]
      public int Id { get; set; }

      /// <summary>
      /// Required
      /// </summary>
      [Required]
      public string Key { get; set; }

      /// <summary>
      /// Required
      /// </summary>
      [Required]
      public string Value { get; set; }

      /*************************************************************************
       * Persistent navigation properties
       *************************************************************************/

   }
}

