//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor
//     https://github.com/msawczyn/EFDesigner
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Tripplanner.DatabaseDesign
{
   public partial class ExternalLink
   {
      partial void Init();

      /// <summary>
      /// Default constructor. Protected due to required properties, but present because EF needs it.
      /// </summary>
      protected ExternalLink()
      {
         Init();
      }

      /// <summary>
      /// Public constructor with required data
      /// </summary>
      /// <param name="url"></param>
      /// <param name="_tripinfo0"></param>
      public ExternalLink(string url, global::Tripplanner.DatabaseDesign.TripInfo _tripinfo0)
      {
         if (string.IsNullOrEmpty(url)) throw new ArgumentNullException(nameof(url));
         this.URL = url;
         if (_tripinfo0 == null) throw new ArgumentNullException(nameof(_tripinfo0));
         _tripinfo0.ExternalLinks.Add(this);

         Init();
      }

      /// <summary>
      /// Static create function (for use in LINQ queries, etc.)
      /// </summary>
      /// <param name="url"></param>
      /// <param name="_tripinfo0"></param>
      public static ExternalLink Create(string url, global::Tripplanner.DatabaseDesign.TripInfo _tripinfo0)
      {
         return new ExternalLink(url, _tripinfo0);
      }

      /*************************************************************************
       * Persistent properties
       *************************************************************************/

      /// <summary>
      /// Identity, Required, Indexed
      /// </summary>
      [Key]
      [Required]
      public int Id { get; set; }

      /// <summary>
      /// Required
      /// </summary>
      [Required]
      public string URL { get; set; }

      /*************************************************************************
       * Persistent navigation properties
       *************************************************************************/

   }
}

