//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor
//     https://github.com/msawczyn/EFDesigner
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Tripplanner.DatabaseDesign
{
   public partial class Transportation
   {
      partial void Init();

      /// <summary>
      /// Default constructor. Protected due to required properties, but present because EF needs it.
      /// </summary>
      protected Transportation()
      {
         Init();
      }

      /// <summary>
      /// Public constructor with required data
      /// </summary>
      /// <param name="type"></param>
      /// <param name="_trip0"></param>
      public Transportation(string type, global::Tripplanner.DatabaseDesign.Trip _trip0)
      {
         if (string.IsNullOrEmpty(type)) throw new ArgumentNullException(nameof(type));
         this.Type = type;
         if (_trip0 == null) throw new ArgumentNullException(nameof(_trip0));
         _trip0.Transportations.Add(this);

         Init();
      }

      /// <summary>
      /// Static create function (for use in LINQ queries, etc.)
      /// </summary>
      /// <param name="type"></param>
      /// <param name="_trip0"></param>
      public static Transportation Create(string type, global::Tripplanner.DatabaseDesign.Trip _trip0)
      {
         return new Transportation(type, _trip0);
      }

      /*************************************************************************
       * Persistent properties
       *************************************************************************/

      /// <summary>
      /// Identity, Required, Indexed
      /// </summary>
      [Key]
      [Required]
      public int Id { get; set; }

      /// <summary>
      /// Required
      /// </summary>
      [Required]
      public string Type { get; set; }

      public DateTime? StartTime { get; set; }

      public DateTime? EndTime { get; set; }

      public byte[] TicketPhoto { get; set; }

      /*************************************************************************
       * Persistent navigation properties
       *************************************************************************/

   }
}

