//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor
//     https://github.com/msawczyn/EFDesigner
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity.Migrations;

namespace Tripplanner.DatabaseDesign
{
   /// <inheritdoc/>
   public sealed partial class TripplannerDbMigrationConfiguration : DbMigrationsConfiguration<Tripplanner>
   {
      partial void Init();

      /// <inheritdoc/>
      public TripplannerDbMigrationConfiguration()
      {
         AutomaticMigrationsEnabled = false;
         AutomaticMigrationDataLossAllowed = false;
         Init();
      }
   }
}
