//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor
//     https://github.com/msawczyn/EFDesigner
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Tripplanner.DatabaseDesign
{
   public partial class WeatherForecast
   {
      partial void Init();

      /// <summary>
      /// Default constructor. Protected due to required properties, but present because EF needs it.
      /// </summary>
      protected WeatherForecast()
      {
         Init();
      }

      /// <summary>
      /// Public constructor with required data
      /// </summary>
      /// <param name="location"></param>
      /// <param name="lasttemperature"></param>
      /// <param name="_tripinfo0"></param>
      public WeatherForecast(string location, int lasttemperature, global::Tripplanner.DatabaseDesign.TripInfo _tripinfo0)
      {
         if (string.IsNullOrEmpty(location)) throw new ArgumentNullException(nameof(location));
         this.Location = location;
         this.LastTemperature = lasttemperature;
         if (_tripinfo0 == null) throw new ArgumentNullException(nameof(_tripinfo0));
         _tripinfo0.WeatherForecasts.Add(this);

         Init();
      }

      /// <summary>
      /// Static create function (for use in LINQ queries, etc.)
      /// </summary>
      /// <param name="location"></param>
      /// <param name="lasttemperature"></param>
      /// <param name="_tripinfo0"></param>
      public static WeatherForecast Create(string location, int lasttemperature, global::Tripplanner.DatabaseDesign.TripInfo _tripinfo0)
      {
         return new WeatherForecast(location, lasttemperature, _tripinfo0);
      }

      /*************************************************************************
       * Persistent properties
       *************************************************************************/

      /// <summary>
      /// Identity, Required, Indexed
      /// </summary>
      [Key]
      [Required]
      public int Id { get; set; }

      /// <summary>
      /// Required
      /// </summary>
      [Required]
      public string Location { get; set; }

      /// <summary>
      /// Required
      /// </summary>
      [Required]
      public int LastTemperature { get; set; }

      /*************************************************************************
       * Persistent navigation properties
       *************************************************************************/

   }
}

